### ISSUE TITLE
Album Tab, Sorting by Artist: Not sorting by Album Artist

### ISSUE THREAD

**Issue by BrennanAyers** [jeffvli/sonixd#115]
**Describe the bug**
When looking at all Albums and changing the sort to be by Artist, it is instead sorting the albums based on _who_ is _on_ the album, not the Album Artist (a distinct field). 

**To Reproduce**
1. Go to 'Albums'
2. Click on sort options
3. Scroll down to 'A-Z (Artist)', click
4. See confusing behavior

**Expected behavior**
In Jellyfin Web and other clients, when sorting Albums A-Z by Artist, it will use the Album Artist field. This allows all albums to be grouped by who the lead is, and disregards the features/second person on a collab album.

**Screenshots**
![image](https://user-images.githubusercontent.com/45154998/144140590-b77bce6b-5d51-4d42-a657-6ef8de7eb03e.png)
This album is listed first because of `$teev`. I would expect it to be sorted by `Joe Kay` (that's how I processed these tracks)
This is actually a good example for comparison between behavior here, and behavior in Jellyfin Web/other clients:
![image](https://user-images.githubusercontent.com/45154998/144140781-a6db725f-80ee-40ba-a15c-ff2022b58143.png)
and in Picard:
![image](https://user-images.githubusercontent.com/45154998/144141071-655a3a41-af2e-4f41-8903-8e40b9a2a283.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: LTSB 1809
 - Sonixd: 0.8.5

**Additional context**
I just downloaded the app and I'm already in love. I think this is the one barrier to entry for me though. Great stuff, hope I can help in the future!

**Comment by BrennanAyers** [comment]
I think this might be the culprit:
https://github.com/jeffvli/sonixd/blob/835dbe89dfd1c8bb3db2c0e8390bcf4d833d4c23/src/components/library/AlbumList.tsx#L122
Correct me if I'm wrong, but the difference here is why you still see Album Artist listed under the album name, despite the sorting not following:
https://github.com/jeffvli/sonixd/blob/835dbe89dfd1c8bb3db2c0e8390bcf4d833d4c23/src/components/library/AlbumList.tsx#L294

**Comment by jeffvli** [comment]
Hey, thanks for opening this issue!

For the A-Z Artist sort, you're correct that it's not using the AlbumArtist field.
To change that, we would change the actual API request that's retrieving the albums.

https://github.com/jeffvli/sonixd/blob/835dbe89dfd1c8bb3db2c0e8390bcf4d833d4c23/src/api/jellyfinApi.ts#L348

As you noted, it's currently using `Artist` instead of `albumArtist`, but that can easily be changed. 

The album page and other parts of the application also need improvements to better support metadata that Jellyfin provides, and there's an existing request (#110) for that which I'll be working on for the next release.

**Comment by BrennanAyers** [comment]
I knew I was getting lost somewhere 😵‍
I also noticed weird sorting on Artist pages, but I'm guessing that would be resolved by the changes you're thinking of for #110 .
Look forward to it, thanks again for making this app!
