### ISSUE TITLE
Remember last song/playlist on startup

### ISSUE THREAD

**Issue by metronidazole** [jeffvli/sonixd#130]
**Is your feature request related to a problem? Please describe.**
It would be nice if this had support for resuming playback of the last song/playlist that was played on startup.

**Describe the solution you'd like**
When starting sonixd, the active song/playlist should be the last one played, and not "unknown title / unknown artist"

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jeffvli** [comment]
This would be a great feature to have. I've been meaning to add it eventually but I've still been thinking about the implementation.

**Comment by kgarner7** [comment]
This is a feature I would also appreciate, and I had a few thoughts about possible implementations. If any of these seem reasonable, let me know and I can try to work on those.

1. Save the entire queue state to some persistent storage. Sublime music (another *sonic player) takes this approach. There are a few main ways I could see this happening
    1. Serialize/compress the queue (`state.entry`) in one file, and the current song (`state.current*`) into another. Whenever the queue changes (or less frequently), write this state back to disk. On load, read the file back to the queue. For best disk usage, this should be compressed (for example, using [zlib](https://nodejs.org/docs/latest-v14.x/api/zlib.html#zlib_zlib)). While this is the easiest option, it will have the highest disk utilization and potential time spent. 
    2.  Similar to above, but instead of storing the raw queue, do some preprocessing. For example, we can extract the artist, genre, album to their own objects, and then just have the queue refer to those. This has the side effect that saving the current state will take longer (although you should be able to do it in one pass), but should hopefully result in less stored to disk (and the option of separate files).
    3. Have the queue state/metadata backed by a database/database-lite. This could just be localstorage, or more specialized tools like sqlite, or similar JS ones like [rxdb](https://github.com/pubkey/rxdb) or [lowdb](https://github.com/typicode/lowdb). This has the potential for the most optimizations, at a cost of more work (and the need for external dependencies).
2. Save only the ids of the songs on the queue, and current id. On load, fetch the remaining metadata from the *sonic/jellyfin server. This makes the state very small, but it does mean that rebuilding the play queue can take a while.
3. Only save the last added album/artist/playlist/song. Determining the current item is a bit challenging, as we may have added a playlist, then some albums, and shuffled again, but there could be some persistent state to store history. Unless your playlist is extremely large, this means we probably don't need to store as much, and we can adopt either 1 or 2 for that state.

To give some concrete numbers, when I enqueued ~4000 elements to the queue and serialized that to JSON, that was around 4.2MB. Compressed with Linux zip, that got it down to 448 KB. With zstd, that was reduced to 192 KB.

**Comment by jeffvli** [comment]
@kgarner7 I was going to look at this soon as well, since I wanted to eventually add support for offline playlist support.

Option 2 could work, but you're correct that rebuilding would not be ideal due to having to make an individual request for each song (especially for Jellyfin which takes a while to fetch).

I'd rather save the entire queue rather than just a subset, so I'd scratch out option 3.

Your option 1 makes the most sense. The way I was planning to do it was what you listed in option `i`. I did a lot of thinking about how I would go about implementing this (as well as offline mode), and I'm somewhat against rolling a db solution like sqlite, and would rather go with json to store the data. Obviously not as efficient as a SQL solution, but all of the API results have been normalized for both Subsonic/Jellyfin APIs so it should be easy to just save the result and plug it into a plain-text json collection. 

Instead of re-writing it to the disk every time the queue changes, the most efficient way would probably be to use the [before-quit](https://www.electronjs.org/docs/latest/api/app#event-before-quit) event on the `main` electron process. That way we can just fetch the `playQueue.entry` state and compress & save it before the app closes.

**Comment by ldexterldesign** [comment]
👋

Is this functionality still working because I'm seeing no saved (view or song) states when I close/open the app 🤷?

Hope to hear back

Cheers

Version: 0.15.3

**Comment by jeffvli** [comment]
@ldexterldesign The "remember window size" functionality was removed due to it breaking the installation a while back. It hasn't been resolved since.

In regards to the saving play queue, it's still working on my side. How are you closing the application? If the application is being closed by your OS (for example when you shut down or reboot the computer) it may not work correctly. Also, I'm unable to test on macOS since I don't have the proper device, so that may be an issue there.

**Comment by ldexterldesign** [comment]
Hi @jeffvli,

Thanks for reply



I'm
