### ISSUE TITLE
Play all songs on Artist Page plays not in order

### ISSUE THREAD

**Issue by Maxplosion** [jeffvli/sonixd#202]
**Describe the bug**
Hi, when playing all songs using the `Play` button on an Artist Page it will play all, but not in the Album Track order but seems to start somewhere in the middle - e.g. with Track 4. 

If I just add the albums to the queue using the `add to queue` button it adds them in the correct order track 1 - track n

**To Reproduce**
1. Go to an Artist
2. Click on Play
3. check queue - tracks are not sorted correctly (double check if shuffle is off)

**Expected behavior**
Albums are played from track 1 to last one after the other.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 0.11.0
 - Server: Jellyfin 10.7.7

**Comment by jeffvli** [comment]
Thanks, confirmed on my side as well.

`Add to queue` from the list view pulls the albums 1 by 1, so that's why it's working properly. The `Play` button (and its accompanying add buttons) uses a single API call to get all songs by the specified artist. It seems like the `SortBy` property isn't working properly for it, at least not in terms of keeping the song index in ascending order.

I can change this behavior, though it will result in more server requests.

**Comment by jeffvli** [comment]
I actually just implemented a client-side sort for the returned entries instead of changing the requests.

Note that the returned entries still may differ between selecting the albums and pressing `Play` from the context menu since the single request ignores songs from albums with `Various Artists` or compilation albums that have a differing artists.

**Comment by Maxplosion** [comment]
I don't know where to put this, but I really like the view by clicking the little "information" button on the now playing list!
the similar tracks might not be correct there most of the time, but its a great list and let's me discover songs I haven't heard in years! love it!

**Comment by jeffvli** [comment]
Glad you like it! The feature was originally requested in #160 and it's still a first iteration design so hopefully expect improvements in the future.
