### ISSUE TITLE
Play all in Genre view

### ISSUE THREAD

**Issue by Maxplosion** [jeffvli/sonixd#239]
Hi, could you add a button to play all tracks in a genre? e.g. I'd like to listen to all my Jazz tracks today and next day to all my Happy Hardcore tracks and so on. 

**Describe the solution you'd like**
I'll select a specific Genre from the `Genre` view.
I see all the albums listed and would like to play them all with a button press (same as it is done in the `Artist detail` view. 
(currently I only know of adding all the albums manually from this view to the queue, maybe I'm missing something?)

Same could be done for Artists and Albums view, as I would assume they have the same logic as the Genre view?

Thanks!

--Using Sonixd 0.13.1 on Jellyfin 10.7.7

**Comment by jeffvli** [comment]
Technically this can already be done by using the `Auto playlist` on the Now Playing page and selecting the genre. I've since removed the 500 song limit on it for Jellyfin so you can specify an infinitely large number to play all tracks of the genre using it.

![image](https://user-images.githubusercontent.com/42182408/154687597-6dc9524c-d073-4cba-a580-1ec6cf67964c.png)

Though I can also add some additional ways for this like you said:
1. Play / Add functionality from right-click context menu on the `Genre` view (maybe also a button that's enabled whenever genres are selected in the list?)
2. Play / Add buttons on the Album page when sorting by a genre

> Same could be done for Artists and Albums view, as I would assume they have the same logic as the Genre view?

What do you mean for the Artists view though?

**Comment by Maxplosion** [comment]
Hi,
I did not see that the limit was removed from the auto playlist, good to know that then already does what I wanted to achieve!

A context menu entry on the specific genre entry in the `Genre `view would be enough for me to be honest (button is just nicer and more consistent). This was also something I initially tried first to do, as it felt natural to expect this functionality there.

With `Artist `view I meant if you select in the sidebar the `Artist` tab and you then get a list of all your artists with their number and a "refresh" button at the top, and to add there a button to `play all`. 
Same as with `Albums` - so both would do the same and queue all the tracks in the library (which might be a lot depending on the library size, so yeah not sure if it's even that great of an idea). I just thought, when you implement the logic for genres doing the same for the Artist/Album tabs might make it more consistent.
