### ISSUE TITLE
Desktop notifications

### ISSUE THREAD

**Issue by woodruffw** [jeffvli/sonixd#245]
**Is your feature request related to a problem? Please describe.**

Sonixd is awesome already, but it would be even more awesome if it supported desktop notifications!

**Describe the solution you'd like**

On each song play, Sonixd would display a native system notification containing:

* The album art
* The album name, current track name, and artist name

**Describe alternatives you've considered**

There's probably a way to hack this together with system events (or MPRIS, on Linux), but it'd probably be flakey and is best "done right once" by the player itself.

**Additional context**

No additional context.

**Comment by jeffvli** [comment]
Technically should be possible since Electron has an API that hooks into each system's notifications natively.

Reference: https://www.electronjs.org/docs/latest/tutorial/notifications

**Comment by jeffvli** [comment]
I've added notifications, but currently it will only show when the song automatically changes. 
This is due to a couple reasons:
- Complexity regarding handling all states where the song can change (using media hotkeys, player bar, tray menu, mpris)
- Native notification behavior starts to lag behind when quickly changing songs (at least on Windows). This behavior would be distracting if quickly switching through songs.

Is this behavior fine for you, or do you think having it always show regardless of how the song changes is important?

**Comment by woodruffw** [comment]
> Is this behavior fine for you, or do you think having it always show regardless of how the song changes is important?

That's great by me! Thanks a ton for implementing it!
