### ISSUE TITLE
Configurable zoom level

### ISSUE THREAD

**Issue by arthurlutz** [jeffvli/sonixd#252]
**Is your feature request related to a problem? Please describe.**
On a new laptop I have a quite high resolution (2560x1600) using an LTS ubuntu most application (especially Electron) provide a way to zoom to avoid having an interface with very small fonts and images. This can also be done with DPI settings but I want to avoid going down that road (for now) .

**Describe the solution you'd like**
Most electron-based apps enable a "Ctrl-+" or "Ctrl-minus" to zoom in/out all the graphical elements. The good one keep this setting from a session to the next. Some can also do this setting in the configuration as 100% / 125% / 150% / 200%.

**Describe alternatives you've considered**
An alternative is to change the resolution using xrandr or other tools. Also I could tweak the size of thumbnails etc but I would still have small buttons and small text.

**Comment by jeffvli** [comment]
I've added zoom hotkeys per your suggestion, using:
- `Ctrl` + `Shift` + `=`
- `Ctrl` + `Shift` + `-`

It increments/decrements in 5% intervals so it can be more fine-tuned than presets.

**Comment by arthurlutz** [comment]
Works great, thanks for such a quick fix !

**Comment by Aiku1** [comment]
@jeffvli Maybe it's only on my machine (Windows 10, latest version of Sonixd) but zooming makes some menus blurry (e.g. the ![settings menu](https://user-images.githubusercontent.com/18646272/162575132-ed42664d-7c8f-4f74-9f7b-2a9ee9dd94f3.png)), especially after 125%.

Also, I'm sure there are some improvements to be made on the speed side of it, I have a pretty decent computer and it still takes seconds to redraw everything.

**Comment by jeffvli** [comment]
@Aiku1 The zoom functionality is using the native Electron [webFrame.setZoomFactor](https://www.electronjs.org/docs/latest/api/web-frame) API to set the zoom levels. I'm not sure there's much I can do regarding the blurriness besides possibly increasing the default font sizes so you don't have to zoom as much.

In terms of performance, where are you seeing issues? My zooms are usually almost instantaneous, besides the dashboard page. The dashboard has a couple issues due to not using any virtual lists, so ~60 images are usually loaded at once.

**Comment by Aiku1** [comment]
@jeffvli Are there no other option for zoom? The rest of the UI is still crisp, but those menus look pretty bad on a hi-res monitor.

You're definitely right, it's way worse on the dashboard, in any other pages it's pretty much instantaneous, except for the reloading of the lists which I'm guessing depend on network and on the server. I'm guessing there's nothing you can really do about that?
