### ISSUE TITLE
Add the ability to 'Shuffle All'

### ISSUE THREAD

**Issue by QuestionableBaboon** [jeffvli/sonixd#276]
Would it be possible to borrow Navidrome UI's 'Shuffle All' button found in the Songs tab please?

According to the Git comments that button works by pulling 200 random titles from the library, adding them to a playlist and hitting play.

Why add this? I'm quite happy with the simplicity of knowing that I curate every track in my library and then relinquishing DJ duty to the PC.
The result is I'm always surprised and engaged with my collection, keeping it fresh and finding hidden gems I wouldn't search for myself.

A Songs tab isn't a requirement or precursor for this. But appreciate that, if this is possible, a button would need to be placed appropriately in the UI. Perhaps a row of buttons like Shuffle All, Shuffle A Genre, etc with "just play me something" functionality on the Dash?

Thank you, and thank you very much for the app!

**Comment by winteriscariot** [comment]
sonixd already has this, it's just not the most obvious.

1. in the lower right of the app, click the 'Miniplayer' button (tooltip just says 'Mini')
2. click the + button in the miniplayer -- the 'Autoplaylist' button
3. Select how many tracks you want (you can include all of them) and then click Play (or + Add to append your current playlist)

This is one thing i really like about Sonixd, the problem with it is that it isn't obvious. I agree that having that 'Autoplaylist' button as a sidebar button would be extra handy, and it seems like it shouldn't be too hard to add, since the function already exists.

**Comment by jeffvli** [comment]
I've also heard similar complaints in the past regarding this. It's also on the "Now Playing" page, but it seems like some people don't use the page.

I'll see if I can add a global (or sidebar) button somewhere like you said.

**Comment by winteriscariot** [comment]
> It's also on the "Now Playing" page

oh cool, i didn't notice that, good to know! i actually do use that page a bit, but i start the autoplaylist with the miniplayer haha

**Comment by QuestionableBaboon** [comment]
Thank you for your guidance @winteriscariot I found it. Understood it's also in the Now Playing too @jeffvli

Couple of things:

- I clicked on Autoplaylist once, but backed out as I thought I was creating a permanent playlist rather than adding tracks to Now Playing. I should have persevered, but the nomenclature is... deceptive?
- I wouldn't think to look in Now Playing to start playing music, that's unintuitive.

That said, please don't think I'm knocking the actual functionality, now I know what I'm looking at. I like it a lot, the ability to go random but also add some guidance with genre and year is very tidy.
I'm in two minds about still fancying a dumb Shuffle All button to complement that now. At the end of the day I think I'd still appreciate it, so you've got escalating control:

1. Full brainless, immediate Shuffle All on the Dash for "just give me music"
2. "I feel like jazz" or, indeed, "I feel like jazz from the 50s" with the autoplaylist
3.  "I feel like this, then this, then this... no, this..." with the full suite of "add to playing now" in the app.

That's what I'm thinking, at least.

Thank you for having a think about this.

**Comment by jeffvli** [comment]
I couldn't find a good place to put any new buttons on the sidebar since I think it's already a bit cluttered.

What I changed:
- Rename `Auto playlist` to `Play Random`
- Add `Play Random` button to the main player bar

I was thinking of naming it `Shuffle All` initially, since that's what it's called on some other players, but in the context of the places where the button is located, I think `Play Random` makes more sense. The new `Play Random` button on the player bar functions as a "dumb" and immediate shuffle play (single click) as opposed to the original version. For the detailed "shuffle all", you'll need to use the buttons either in the "Now Playing" or "Mini Player" views. I think that is a good enough compromise for people who don't care for the filtering and just want a quick set of songs.

![image](https://user-images.githubusercontent.com/42182408/162143745-4a0cd8c7-fbe8-498f-8e5c-4fb3cabadddb.png)
