### ISSUE TITLE
Add default column sorting behaviour.

### ISSUE THREAD

**Issue by nfst** [jeffvli/sonixd#47]
**Is your feature request related to a problem? Please describe.**
When opening the album list, the albums are sorted alphabetically by title, a possibility of choosing the default sorting parameter (eg. release year) would be handy.

**Describe the solution you'd like**
Choosing the default sorting column in Look & Feel.

**Comment by jeffvli** [comment]
I can add this alongside #40.

**Comment by nfst** [comment]
That would be a great combination, thanks for taking it into consideration!

**Comment by jeffvli** [comment]
I'm changing the implementation slightly since I couldn't think of a clean way to handle the config component for this.
Column sort is now persistent throughout your session (until you close the application), so you'll still need to apply the sort once per session.

I can possibly add the sort columns to the settings as well to make it always persist between sessions (but not sure if it makes sense).
