### ISSUE TITLE
Album art doesn't show in taskbar thumbnail when sonixd is minimized

### ISSUE THREAD

**Issue by bwat47** [jeffvli/sonixd#73]
Steps to Re-create (windows OS)
1. Launch sonixd
2. Start playing a song
3. Hover over the taskbar thumbnail, and you should see the album art being displayed above the playback controls (as expected)
4. Minimize sonixd
5. Hover over the taskbar thumbnail again, and you'll now see the album art is not displaying:

![image](https://user-images.githubusercontent.com/1442520/140569183-9aeeb65b-f605-42fc-a100-f8582b2e0efd.png)

NOTE: I think this started happening in version 0.5.0

**Comment by jeffvli** [comment]
Unfortunately I don't think was working properly pre-0.5.0 either. This seems to be a limitation of Electron, where I believe a snapshot of the main window is taken before being minimized. This is an issue because the taskbar thumbnail image is a crop of the player bar in the main window using [setThumbnailClip](https://www.electronjs.org/docs/latest/api/browser-window#winsetthumbnailclipregion-windows). Electron doesn't have a way to add a static image as the taskbar thumbnail.

What I can do is to revert it to the default taskbar thumbnail behavior when the window is minimized like so:
![image](https://user-images.githubusercontent.com/42182408/140577054-ffbfafeb-63ef-45fa-ac0f-283144464075.png)

And when the window is restored, it'll go back to the cover image.

**Comment by bwat47** [comment]
I think what caused me to think that it worked previously, was that I have a windows 10 machine and a windows 11 machine.

On the windows 10 machine I see the issue when minimizing sonixd, but for some reason on windows 11 it does keep showing the thumbnail even after minimizing (even in v 0.5.0)

**Comment by jeffvli** [comment]
That makes sense!

I was on a W11 machine when I developed this feature and have since reverted back to W10. I'll add to keep the current functionality on W11 but revert to the window view on W10 when minimizing.
