### ISSUE TITLE
AUR package 

### ISSUE THREAD

**Issue by r2binx** [jeffvli/sonixd#90]
Hi,
because I really enjoy your project I just created an AUR package for your AppImage to simplify installation on arch based distros. You can check it out [here](https://aur.archlinux.org/packages/sonixd-appimage/).
I'll try my best to maintain it but due to the nature of it being an AppImage there shouldn't be much to do anyway.
Let me know if I should do a PR to put it into the readme

**Comment by jeffvli** [comment]
Awesome! Definitely, create a PR and add some instructions under the installation section regarding your package. 

Though I have one question before that: Sonixd currently performs auto updates using [electron-updater](https://www.npmjs.com/package/electron-updater) which is part of the [electron-builder](https://github.com/electron-userland/electron-builder) package that is used to build the binaries. Do you know (or could you test) how your AUR package responds to the auto update request?

You would need to:
1. Build an AUR package for 0.6.0
2. Run/Install the 0.6.0 package
3. See if anything happens when you run 0.6.0

Using the AppImage, you would usually get an OS popup notification within 10-20 seconds that the latest version was downloaded automatically. Though if this functionality breaks with the AUR package, then I would need to add an option to disable the auto update check.

**Comment by r2binx** [comment]
Cool, that electron-updater is really neat!
But currently nothing would happen because the file is owned by the root user after installation from the AUR and only it is allowed to write. I could of course change the permissions but that isn't really common there AFAIK. 
If I would then there's no way that I'm aware of which would inform the package manager that it's already up-to-date and it would just overwrite it with the next AUR update.

I haven't looked at the update mechanism yet, does it always download the update? In that case it might be useful if it was possible to disable the auto updates.

It's a bit unfortunate but that's the tradeoff if you install it this way.

**Comment by jeffvli** [comment]
> I haven't looked at the update mechanism yet, does it always download the update? In that case it might be useful if it was possible to disable the auto updates.

Yes, it forces the download automatically when it detects a new release on this repo. [(ref)](https://github.com/jeffvli/sonixd/blob/1855d6a7b341eb6314892fed5ed54909fc513a0a/src/main.dev.js#L467)

From what I understand (and I could be wrong), the AppImage file isn't replaced, but the latest version is just installed alongside the previous one, to which the AppImage manager points to the newest binary as the latest. 

Either way, I'll add in a checkbox config to turn off the auto updates so in the case that it causes problems with the AUR.

**Comment by r2binx** [comment]
> From what I understand (and I could be wrong), the AppImage file isn't replaced, but the latest version is just installed alongside the previous one, to which the AppImage manager points to the newest binary as the latest.

Oh I see but regardless the permission would be denied in that case as well:
`drwxr-xr-x root  root  4.0K Wed Nov 17 19:59:13 2021  sonixd-appimage`

I never really thought about that, I've got quite a few AppImages installed from the AUR that probably try to update automatically, quite the waste of bandwidth lol

Thanks!
